version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    environment:
      - UVICORN_CMD=uvicorn app.main:app --host 0.0.0.0 --port 8000
    command: ["sh", "-c", "$$UVICORN_CMD"]
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/build
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped
