services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - UVICORN_CMD=uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  frontend:
    build:
      context: ./frontend
      args:
        HOMEPAGE: ""
    ports:
      - "3000:80"
    depends_on:
      - backend



  cube-ai-agent:
    build:
      context: ./cube-ai-agent
    ports:
      - "8003:8000"
    env_file:
      - ./cube-ai-agent/.env
